package: vector_maps
version: '1.1.1'
author: 'KLXM'
supportpage: 'https://github.com/KLXM/vector_maps'
requires:
  php: '>=8.1'
  redaxo: '>=5.14'

page:
  title: 'translate:vector_maps_title'
  perm: 'vector_maps[]'
  icon: 'rex-icon rex-icon-vector-maps'
  subpages:
    readme:
      title: 'translate:vector_maps_readme'
      subPath: README.md
    demo:
      title: 'translate:vector_maps_demo'
      subpages:
        overview:
          title: 'translate:vector_maps_demo_overview'
        basic:
          title: 'translate:vector_maps_demo_basic'
        nearby:
          title: 'translate:vector_maps_demo_nearby'
        advanced:
          title: 'translate:vector_maps_demo_advanced'
    themes:
      title: 'translate:vector_maps_themes'
    settings:
      title: 'translate:vector_maps_settings'
